/*
 * QWHeapChg.java
 *
 * Created on 16 January 2009, 13:48
 */

package com.sterlingcommerce.emea.support.l2.qwa;
import java.awt.Font;
import java.util.*;
/**
 *
 * @author  AAuklend
 */
public class QWHeapChg extends javax.swing.JDialog {

    /** Creates new form QWHeapChg */
    public QWHeapChg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public QWHeapChg(java.awt.Frame parent, String title, boolean modal) {
        super(parent,title, modal);
        initComponents();
    }
    private ArrayList tokenize(String str) {
        ArrayList al = new ArrayList();
	int i0 = 0;
        for ( StringTokenizer st = new StringTokenizer(str,";"); st.hasMoreTokens();) {
            al.add(i0++,(String)st.nextToken()); 
        }
        return al;
    }
    
    public void createTable(int size ){
       jTextField1.setFont(new Font("Verdana",Font.PLAIN,14));
       if (size == 0) {
          jTextField1.setText("     No heap information this sampling ");
          return;
       }
       jTable1 =  new  javax.swing.JTable(size,4);
       javax.swing.table.TableColumn column = new javax.swing.table.TableColumn();
       jTable1.getColumnModel().getColumn(0).setHeaderValue("Time");
       jTable1.getColumnModel().getColumn(1).setHeaderValue("Action");
       jTable1.getColumnModel().getColumn(2).setHeaderValue("Old Size(GB)");
       jTable1.getColumnModel().getColumn(3).setHeaderValue("Free Mem(%)");
       jTextField1.setText("  Memory Expansion / Contraction during the sampling periode");
       jScrollPane1.setViewportView(jTable1);
    }
    public void updateTable(ArrayList al){
        if (al.size() == 0)
            return;
        int i = 0;    
        for (Iterator it = al.iterator(); it.hasNext();) {
            ArrayList al2 = tokenize((String)it.next());
            jTable1.setValueAt(al2.get(0),i,0);
            jTable1.setValueAt(al2.get(1),i,1);
            jTable1.setValueAt(al2.get(2),i,2);
            jTable1.setValueAt(al2.get(3),i,3);
            i++;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(150, 70, 0, 0));

        jTextField1.setText("jTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Time", "Action", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QWHeapChg dialog = new QWHeapChg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
